addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - g++-8
      - cmake
      - doxygen

before_install:
   - sudo apt-get install libboost-test-dev -y
   - echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
   - sudo apt-get update -qq
   - sudo apt-get install libgtest-dev
   - sudo apt-get install cmake
   - sudo apt-get install doxygen -y
   - sudo apt-get update -qq
install:
   - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 999 --slave /usr/bin/g++ g++ /usr/bin/g++-8
   - sudo update-alternatives --auto gcc
script:
   # Install gcc & g++
   - sudo ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
   - sudo ln -s /usr/bin/g++-8 /usr/local/bin/g++
   - export CC=/usr/bin/gcc-8
   - export CXX=/usr/bin/g++-8
   - gcc -v && g++ -v && cmake --version
   # Install GTest
   - cd /usr/src/gtest
   - sudo cmake CMakeLists.txt
   - sudo make
   - sudo cp *.a /usr/lib
   - cd -
   # Build project
   - cmake .
   - make 
   - cmake --build . --target package
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    local-dir: html
    on:
       branch: master
    provider: script
    skip_cleanup: true
    script:
            - curl -T print_ip-0.0.1$TRAVIS_BUILD_NUMBER-Linux.deb -uinlineboss:$BINTRAY_API_KEY "https://api.bintray.com/content/facs/OTUS/Allocator/$TRAVIS_BUILD_NUMBER/print_ip-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
